### ISSUE TITLE
Is this piece of code intentionally left out from being compiled?

### ISSUE THREAD

**Issue by abhishekacharya-official** [RudrakshTuwani/Football-Data-Analysis#1]
In Football-Data-Analysis-and-Prediction/Analysis/**Football.Odds.Analysis.ipynb** 

After the output of 78th box input this is mentioned,

> col_df = list(mw_dist_38.columns) range_df = abs(col_df[0]) + abs(col_df[-1]) size = 6 # Finds the lower limit of data which is divisibile by size lcl = abs(col_df[0]) + abs(col_df[0] % size) if col_df[0] < 0: lcl = -lcl # Finds the upper limit ucl = col_df[-1] + (col_df[-1] % size) # Generates ideal columns for dataframe cols = [i for i in range(lcl,0)] + [i for i in range(ucl+1)] cols # Fills in for missing columns of dataframe for col in cols: if col not in col_df: mw_dist_38[col] = [0,0,0] # Sorts the column in ascending order and gets column which are divisible by size mw_dist_38.sort(axis=1,ascending=True, inplace=True) cols_sizew = [i for i in cols if i % size == 0 ] # Creates new df and assigns value to it mw_dist_new = pd.DataFrame() # Groups columns for col in cols_sizew: if col < 0: mw_dist_new[col] = (mw_dist_38[col] + mw_dist_38[col+1] + mw_dist_38[col+2] + mw_dist_38[col+3] + mw_dist_38[col+4] + mw_dist_38[col+5]) elif col == 0: mw_dist_new[col] = mw_dist_38[col] else: mw_dist_new[col] = (mw_dist_38[col] + mw_dist_38[col-1] + mw_dist_38[col-2] + mw_dist_38[col-3] + mw_dist_38[col-4] + mw_dist_38[col-5]) mw_dist_new.T.plot(kind='bar', stacked = True, figsize=[30,10], color = ['steelblue','sandybrown', 'turquoise'])mw_dist_38.rename(columns = {0:'HomeWins', 1:'AwayWins', 2:'Draws', 3:'TotalMatches'}, inplace =True) mw_dist_38.plot(kind='bar', stacked = True, figsize=[30,10], color = ['steelblue','sandybrown', 'turquoise'])df = mw_dist_38.T 

Moreover mw_dist_38 is not present in previous code.

Please make it clear.  :)

**Comment by RudrakshTuwani** [comment]
Hi Abhishek, thank you for your interest in the project. This was my first project using Python for Data Science and as a result, the code may be ambiguous and repetitive at times. Based on a quick glance, indeed this part has been commented out and should not be run.

**Comment by abhishekacharya-official** [comment]
Thanks 👍. 
I'm studying Data Science using Python and referring to project such as yours for better understanding.
